package dsa_ca1;

/**
 *
 * @author yaros
 */
public class BicycleGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(BicycleGUI.class.getName());
    
    // Variables/Objects
    private String inputString, displayText;
    private int inputInt, counter, size;
    private boolean empty;
    ListStation mySLL = new ListStation();
    private BStation selectedStation;
    private boolean isInt;

    /**
     * Creates new form BicycleGUI
     */
    public BicycleGUI() {
        initComponents();
        counter = 1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        outputDisplay = new javax.swing.JLabel();
        displayStation = new javax.swing.JButton();
        selectStationButton = new javax.swing.JButton();
        addStationButton = new javax.swing.JButton();
        removeStationButton = new javax.swing.JButton();
        textInput = new javax.swing.JTextField();
        viewHistory = new javax.swing.JButton();
        removeBikeButton = new javax.swing.JButton();
        addBikeButton = new javax.swing.JButton();
        dummyData = new javax.swing.JButton();
        viewDetails = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(661, 560));
        setPreferredSize(new java.awt.Dimension(661, 493));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        title.setText("Bicycle Station App");
        getContentPane().add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, 310, 50));

        outputDisplay.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(outputDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 260, 310));

        displayStation.setText("Display Stations");
        displayStation.addActionListener(this::displayStationActionPerformed);
        getContentPane().add(displayStation, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 120, -1));

        selectStationButton.setText("Select Station");
        selectStationButton.addActionListener(this::selectStationButtonActionPerformed);
        getContentPane().add(selectStationButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 150, 120, -1));

        addStationButton.setText("Add Station");
        addStationButton.addActionListener(this::addStationButtonActionPerformed);
        getContentPane().add(addStationButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, 120, -1));

        removeStationButton.setText("Remove Station");
        removeStationButton.addActionListener(this::removeStationButtonActionPerformed);
        getContentPane().add(removeStationButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 150, 120, -1));
        getContentPane().add(textInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, 340, 40));

        viewHistory.setText("View Bike History");
        viewHistory.addActionListener(this::viewHistoryActionPerformed);
        getContentPane().add(viewHistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 270, 140, -1));

        removeBikeButton.setText("Remove Bike");
        removeBikeButton.addActionListener(this::removeBikeButtonActionPerformed);
        getContentPane().add(removeBikeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 230, 120, -1));

        addBikeButton.setText("Queue Bike");
        addBikeButton.addActionListener(this::addBikeButtonActionPerformed);
        getContentPane().add(addBikeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, 120, -1));

        dummyData.setText("Test Data");
        dummyData.addActionListener(this::dummyDataActionPerformed);
        getContentPane().add(dummyData, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 440, 120, -1));

        viewDetails.setText("View Current Queue");
        viewDetails.addActionListener(this::viewDetailsActionPerformed);
        getContentPane().add(viewDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, 140, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addStationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStationButtonActionPerformed
        inputString = textInput.getText(); // Gets input from the text field
        BStation sta = new BStation(inputString); // Gets the BStation object class with its own queue and stack and sets it as the object variable "sta"
        mySLL.add(sta); // The object "sta" is added to the arraylist
    }//GEN-LAST:event_addStationButtonActionPerformed

    private void removeStationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeStationButtonActionPerformed
        // Takes input from user and checks if it can be turned into an integer
        try {
            inputInt = Integer.parseInt(textInput.getText());
            isInt = true;
        } catch (Exception e) {
            isInt = false;
        }
        // If the input is not an integer type, prompt the user to enter a valid number
        if (isInt == false) {
            outputDisplay.setText("<html>Invalid or no number inputed.<br>Please use a number to select a station from the list</html>");
        } else {
            // Checks if the inputted integer is outside the arraylist index range
            int listSize = mySLL.size();
            if (inputInt > listSize || inputInt <= 0) {
                outputDisplay.setText("<html>Invalid or no number inputed.<br>Please use a number to select a station from the list</html>");
                return;
            }
            mySLL.remove(inputInt); // Removes the object from the list
            displayText = mySLL.printList();
            outputDisplay.setText(displayText); // Reprints the list to show updated list
        }
    }//GEN-LAST:event_removeStationButtonActionPerformed

    private void displayStationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayStationActionPerformed
        // Displays the linked list contents
        displayText = mySLL.printList();
        outputDisplay.setText(displayText);
    }//GEN-LAST:event_displayStationActionPerformed

    private void selectStationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectStationButtonActionPerformed
        // Takes input from user and checks if it can be turned into an integer
        try {
            inputInt = Integer.parseInt(textInput.getText());
            isInt = true;
        } catch (Exception e) {
            isInt = false;
        }
        // If the input is not an integer type, prompt the user to enter a valid number
        if (isInt == false) {
            outputDisplay.setText("<html>Invalid or no number inputed.<br>Please use a number to select a station from the list</html>");
        } else {
            // Checks if the inputted integer is outside the arraylist index range
            int listSize = mySLL.size();
            if (inputInt > listSize || inputInt <= 0) {
                outputDisplay.setText("<html>Invalid or no number inputed.<br>Please use a number to select a station from the list</html>");
                return;
            }
            selectedStation = (BStation) mySLL.get(inputInt); 
            displayText = "<html> Parking station selected:<br>" + inputInt + ": " + selectedStation + "</html>";
            outputDisplay.setText(displayText);
        }
    }//GEN-LAST:event_selectStationButtonActionPerformed

    private void dummyDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dummyDataActionPerformed
        // Sample test data to show app functionality
        mySLL.add(new BStation("National College of Ireland"));
        mySLL.add(new BStation("Docklands Dublin"));
        mySLL.add(new BStation("Spencer Dock"));
        mySLL.add(new BStation("Hanover Quay"));
        mySLL.add(new BStation("Mayor Street Upper"));
    }//GEN-LAST:event_dummyDataActionPerformed

    private void addBikeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBikeButtonActionPerformed
        // Enqueues a bike to the selected stations queue
        selectedStation.getQueue().enqueue(textInput.getText());
        System.out.println("You have enqueued a bike");
    }//GEN-LAST:event_addBikeButtonActionPerformed

    private void removeBikeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeBikeButtonActionPerformed
        // Dequeues a bike to the selected stations queue
        selectedStation.getQueue().dequeue();
        selectedStation.getStack().push(textInput.getText());
    }//GEN-LAST:event_removeBikeButtonActionPerformed

    private void viewDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewDetailsActionPerformed
        // Checks if the queue is empty
        empty = selectedStation.getQueue().isEmpty();
        // If not empty, tells the user the current size of the queue
        if (empty == false) {
            size = selectedStation.getQueue().size();
            outputDisplay.setText("Bikes waiting for parking spot: " + size);
        } else {
            outputDisplay.setText("The stations queue is empty"); // Otherwise, notify the user that the queue is empty
        }
        
    }//GEN-LAST:event_viewDetailsActionPerformed

    private void viewHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewHistoryActionPerformed
        // Gets the stack size of the selected stations stack
        size = selectedStation.getStack().size();
        outputDisplay.setText("This station had " + size + " bikes parked.");
    }//GEN-LAST:event_viewHistoryActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new BicycleGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBikeButton;
    private javax.swing.JButton addStationButton;
    private javax.swing.JButton displayStation;
    private javax.swing.JButton dummyData;
    private javax.swing.JLabel outputDisplay;
    private javax.swing.JButton removeBikeButton;
    private javax.swing.JButton removeStationButton;
    private javax.swing.JButton selectStationButton;
    private javax.swing.JTextField textInput;
    private javax.swing.JLabel title;
    private javax.swing.JButton viewDetails;
    private javax.swing.JButton viewHistory;
    // End of variables declaration//GEN-END:variables
}
